version: '3.9'

services:
  jira:
    image: atlassian/jira-software:9.15.0
    container_name: jira_app
    ports:
      - "8081:8080"
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jirapass
    depends_on:
      - db
    volumes:
      - jira_data:/var/atlassian/application-data/jira

  db:
    image: postgres:15
    container_name: jira_db
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jirapass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  jira_data:
  db_data:
